spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin2021
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  type-aliases-package: example.board
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500

log4jdbc:
    spylogdelegator:
      name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
    dump:
      sql:
        maxlineloength: 0