spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin2021
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: example.board    #매퍼용 클래스가 위치한 경로
  mapper-locations: mapper/**/*.xml      #xml파일이위치한 경로/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500